"""Document generation tool — produces polished .docx files using python-docx.

Converts structured DocumentSection objects into a professionally formatted
Word document with headings, paragraphs, bullet lists, tables, and metadata.
"""

from __future__ import annotations

import logging
import os
import re
from datetime import datetime
from pathlib import Path

from docx import Document
from docx.shared import Inches, Pt, Cm, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT

from app.models.schemas import DocumentSection

logger = logging.getLogger(__name__)


class DocumentTool:
    """Generates professional .docx files from structured section data."""

    def __init__(self, output_dir: str = "output") -> None:
        self._output_dir = Path(output_dir)
        self._output_dir.mkdir(parents=True, exist_ok=True)

    def generate(
        self,
        title: str,
        document_type: str,
        sections: list[DocumentSection],
        assumptions: list[str],
    ) -> str:
        """Generate a .docx file from the provided sections.

        Args:
            title: Document title (derived from request).
            document_type: The type of document (e.g., 'Project Proposal').
            sections: Ordered list of document sections.
            assumptions: Assumptions made during planning.

        Returns:
            Absolute file path of the generated .docx file.
        """
        doc = Document()

        self._apply_styles(doc)
        self._add_title_page(doc, title, document_type)
        self._add_assumptions_section(doc, assumptions)
        self._add_content_sections(doc, sections)
        self._add_footer(doc, document_type)

        # Generate safe filename
        safe_title = re.sub(r"[^\w\s-]", "", title)[:50].strip().replace(" ", "_")
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{safe_title}_{timestamp}.docx"
        filepath = self._output_dir / filename

        doc.save(str(filepath))
        logger.info("Document saved: %s", filepath)
        return str(filepath.resolve())

    # ------------------------------------------------------------------
    # Private helpers — document structure
    # ------------------------------------------------------------------

    def _apply_styles(self, doc: Document) -> None:
        """Configure base document styles for a professional look."""
        style = doc.styles["Normal"]
        font = style.font
        font.name = "Calibri"
        font.size = Pt(11)
        font.color.rgb = RGBColor(0x2D, 0x2D, 0x2D)

        paragraph_format = style.paragraph_format
        paragraph_format.space_after = Pt(6)
        paragraph_format.line_spacing = 1.15

    def _add_title_page(
        self, doc: Document, title: str, document_type: str
    ) -> None:
        """Add a professional title page."""
        # Add some spacing
        for _ in range(4):
            doc.add_paragraph("")

        # Document type label
        type_para = doc.add_paragraph()
        type_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        type_run = type_para.add_run(document_type.upper())
        type_run.font.size = Pt(14)
        type_run.font.color.rgb = RGBColor(0x00, 0x6D, 0x77)
        type_run.font.bold = True

        # Main title
        title_para = doc.add_paragraph()
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title_run = title_para.add_run(title)
        title_run.font.size = Pt(28)
        title_run.font.bold = True
        title_run.font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E)

        # Divider line
        divider = doc.add_paragraph()
        divider.alignment = WD_ALIGN_PARAGRAPH.CENTER
        div_run = divider.add_run("━" * 40)
        div_run.font.color.rgb = RGBColor(0x00, 0x6D, 0x77)
        div_run.font.size = Pt(12)

        # Metadata
        date_str = datetime.now().strftime("%B %d, %Y")
        meta_para = doc.add_paragraph()
        meta_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        meta_run = meta_para.add_run(
            f"Generated by AI Agent\n{date_str}\nConfidential"
        )
        meta_run.font.size = Pt(10)
        meta_run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

        # Page break after title
        doc.add_page_break()

    def _add_assumptions_section(
        self, doc: Document, assumptions: list[str]
    ) -> None:
        """Add a section listing assumptions made by the agent."""
        if not assumptions:
            return

        heading = doc.add_heading("Assumptions & Notes", level=1)
        self._style_heading(heading)

        intro = doc.add_paragraph(
            "The following assumptions were made by the AI agent "
            "to fill in missing information and produce a complete document:"
        )
        intro.style = doc.styles["Normal"]

        for assumption in assumptions:
            bullet = doc.add_paragraph(assumption, style="List Bullet")
            bullet.paragraph_format.space_after = Pt(3)

        doc.add_paragraph("")  # Spacer

    def _add_content_sections(
        self, doc: Document, sections: list[DocumentSection]
    ) -> None:
        """Add all document content sections with formatting."""
        for section in sections:
            # Heading
            level = min(section.level, 3)  # Cap at heading level 3
            heading = doc.add_heading(section.heading, level=level)
            self._style_heading(heading)

            # Main content — split into paragraphs
            if section.content:
                paragraphs = section.content.split("\n\n")
                for para_text in paragraphs:
                    para_text = para_text.strip()
                    if para_text:
                        p = doc.add_paragraph(para_text)
                        p.style = doc.styles["Normal"]

            # Bullet points
            if section.bullet_points:
                for bp in section.bullet_points:
                    bullet = doc.add_paragraph(bp, style="List Bullet")
                    bullet.paragraph_format.space_after = Pt(2)

            # Table
            if section.table_data and len(section.table_data) >= 2:
                self._add_table(doc, section.table_data)

            # Add spacing between sections
            doc.add_paragraph("")

    def _add_table(self, doc: Document, table_data: list[list[str]]) -> None:
        """Add a formatted table to the document."""
        if not table_data:
            return

        num_cols = len(table_data[0])
        table = doc.add_table(rows=1, cols=num_cols, style="Light Grid Accent 1")
        table.alignment = WD_TABLE_ALIGNMENT.CENTER

        # Header row
        header_cells = table.rows[0].cells
        for idx, header_text in enumerate(table_data[0]):
            header_cells[idx].text = str(header_text)
            for paragraph in header_cells[idx].paragraphs:
                for run in paragraph.runs:
                    run.font.bold = True
                    run.font.size = Pt(10)

        # Data rows
        for row_data in table_data[1:]:
            row_cells = table.add_row().cells
            for idx, cell_text in enumerate(row_data):
                if idx < num_cols:
                    row_cells[idx].text = str(cell_text)
                    for paragraph in row_cells[idx].paragraphs:
                        for run in paragraph.runs:
                            run.font.size = Pt(10)

    def _add_footer(self, doc: Document, document_type: str) -> None:
        """Add a simple footer with document metadata."""
        doc.add_page_break()

        footer_para = doc.add_paragraph()
        footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        divider_run = footer_para.add_run("━" * 40)
        divider_run.font.color.rgb = RGBColor(0xCC, 0xCC, 0xCC)

        disclaimer = doc.add_paragraph()
        disclaimer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        disc_run = disclaimer.add_run(
            f"This {document_type.lower()} was autonomously generated by an AI Agent.\n"
            "All data and figures are illustrative and should be validated.\n"
            f"© {datetime.now().year} Acme Technologies Inc."
        )
        disc_run.font.size = Pt(8)
        disc_run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)

    @staticmethod
    def _style_heading(heading) -> None:
        """Apply consistent styling to headings."""
        for run in heading.runs:
            run.font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E)
